/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ajana' at '9/11/16 4:53 PM' with Gradle 2.14.1
 *
 * @author ajana, @date 9/11/16 4:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
